version: "3.8"

services:
  db:
    image: postgres:16
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: comments
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./comment-app
    container_name: backend
    depends_on:
      - db
    ports:
      - "8000:8000"
      - "5555:5555"
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/comments

volumes:
  pgdata:
